gui:
  border: single
  theme:
    # Catppuccin Frappe
    activeBorderColor:
      - '#838ba7'
      - bold
    inactiveBorderColor:
      - '#626880'
    optionsTextColor:
      - '#8caaee'
    selectedLineBgColor:
      - '#414559'
    cherryPickedCommitBgColor:
      - '#51576d'
    cherryPickedCommitFgColor:
      - '#8caaee'
    unstagedChangesColor:
      - '#e78284'
    defaultFgColor:
      - '#c6d0f5'
    searchingActiveBorderColor:
      - '#e5c890'
  authorColors:
    '*': '#babbf1'

  #   # Catppuccin Macchiato
  #   activeBorderColor:
  #     - "#939ab7"
  #     - bold
  #   inactiveBorderColor:
  #     - "#5b6078"
  #   optionsTextColor:
  #     - "#8aadf4"
  #   selectedLineBgColor:
  #     - "#363a4f"
  #   cherryPickedCommitBgColor:
  #     - "#494d64"
  #   cherryPickedCommitFgColor:
  #     - "#b7bdf8"
  #   unstagedChangesColor:
  #     - "#ed8796"
  #   defaultFgColor:
  #     - "#cad3f5"
  #   searchingActiveBorderColor:
  #     - "#eed49f"
  # authorColors:
  #   "*": "#b7bdf8"

  #   # Catppuccin Mocha
  #   activeBorderColor:
  #     - '#9399b2'
  #     - bold
  #   inactiveBorderColor:
  #     - '#585b70'
  #   optionsTextColor:
  #     - '#89b4fa'
  #   selectedLineBgColor:
  #     - '#313244'
  #   cherryPickedCommitBgColor:
  #     - '#45475a'
  #   cherryPickedCommitFgColor:
  #     - '#89b4fa'
  #   unstagedChangesColor:
  #     - '#f38ba8'
  #   defaultFgColor:
  #     - '#cdd6f4'
  #   searchingActiveBorderColor:
  #     - '#f9e2af'
  # authorColors:
  #   '*': '#b4befe'

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  
  log:
    showGraph: always
